version: "3.7"

services:
  api:
    build:
      context: ./backend/Motorsport.WebApi
      dockerfile: Dockerfile
    container_name: MotorsportAPI
    depends_on:
      - mssql
    ports:
      - "5000:80"
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: React
    ports:
      - '8787:80'
    depends_on:
      - api
    volumes:
      - '.:/client/'
      - '/client/node_modules'
  mssql:
    build:
      context: ./mssql
      dockerfile: Dockerfile
    restart: always
    container_name: mssql
    ports:
      - "1433:1433"
    expose:
      - 1433
    volumes:
      - ./mssql_volume:/var/opt/mssql
