version: "3.7"

services:
  api:
    build:
      context: ./backend/Motorsport.WebApi
      dockerfile: Dockerfile
    container_name: asp-api
    environment:
      DBServer: "mssql"
      DBUser: "sa"
      DBPort: "1433"
      DBPassword: "1Secure@Password1"
    depends_on:
      - mssql
    ports:
      - "5000:80"
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-ui
    ports:
      - '8787:80'
    depends_on:
      - api
    volumes:
      - '.:/client/'
      - '/client/node_modules'
  mssql:
    build: ./mssql
    ports:
    - '1700:1433'
    container_name: mssql
